"""Meeting brochure generator — arms the rep before meeting a lead.

Takes a HubSpot account, composes a meeting brief/brochure grounded ONLY in
CRM data (real signal, real contacts, evidence), generates it with Gamma and
posts the URL back on the company as a note. No invented specs, ever.

The Lovable "Prepare meeting" button triggers this flow.

Usage:
    python -m backend.agents.brochure --company "Sepalumic"
"""

import argparse
import os
import time

import httpx
from dotenv import load_dotenv

load_dotenv()

HS = "https://api.hubapi.com"
GAMMA = "https://public-api.gamma.app/v1.0/generations"

OFFER = """Industrial equipment and services for aluminium-extrusion plants:
high-temperature furnace and press-line support, maintenance programs, and
plant-project engineering. (Demo persona offer — replace with the client's
real offer copy at onboarding.)"""


def hs_headers():
    return {"Authorization": f"Bearer {os.environ['HUBSPOT_TOKEN']}",
            "Content-Type": "application/json"}


def fetch_account(client, name):
    r = client.post(f"{HS}/crm/v3/objects/companies/search", headers=hs_headers(), json={
        "filterGroups": [{"filters": [{"propertyName": "name", "operator": "CONTAINS_TOKEN", "value": name}]}],
        "properties": ["name", "domain", "city", "description", "gtm_signal", "gtm_signal_date", "gtm_priority"],
        "limit": 1})
    results = r.json()["results"]
    if not results:
        raise SystemExit(f"no company matching '{name}'")
    comp = results[0]
    a = client.get(f"{HS}/crm/v4/objects/companies/{comp['id']}/associations/contacts",
                   headers=hs_headers()).json()
    contacts = []
    for assoc in a.get("results", [])[:3]:
        cr = client.get(f"{HS}/crm/v3/objects/contacts/{assoc['toObjectId']}"
                        "?properties=firstname,lastname,jobtitle,email,gtm_provenance",
                        headers=hs_headers()).json()
        contacts.append(cr["properties"])
    return comp, contacts


def compose(comp, contacts):
    p = comp["properties"]
    who = "\n".join(f"- **{c.get('firstname','')} {c.get('lastname','')}** — {c.get('jobtitle') or 'role tbc'}"
                    + (f" · {c['email']}" if c.get("email") else " · phone/email via manual search")
                    for c in contacts) or "- Decision-makers flagged for manual search"
    signal = p.get("gtm_signal") or "No dated signal on file — discovery meeting."
    return f"""# Meeting brief — {p['name']}
Prepared by the GTM engine · {p.get('city') or ''} · priority: {p.get('gtm_priority') or 'watch'}
---
# Why now — their moment
{signal}
This is the window: decisions around this project are being shaped now. Arriving with this context is the difference between a supplier call and a peer conversation.
---
# Who you are meeting
{who}
---
# What we bring to this project
{OFFER}
Map each pillar to their project above — lead with the one their signal points at.
---
# Conversation angles
- Open with their project, not with us: reference the investment above in the first minute.
- In a finite market every account is precious: the goal of meeting one is a relationship, not a close.
- Next step to propose: a site visit or a technical review tied to their project timeline.
---
# About this document
Generated by the finite-market GTM engine from live CRM data (signal, evidence, contacts). Facts above trace to sources on the account record; nothing is invented.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--company", required=True)
    args = ap.parse_args()
    with httpx.Client(timeout=60) as client:
        comp, contacts = fetch_account(client, args.company)
        text = compose(comp, contacts)
        r = client.post(GAMMA, headers={"X-API-KEY": os.environ["GAMMA_API_KEY"]},
                        json={"inputText": text, "textMode": "preserve", "format": "document",
                              "numCards": 6,
                              "additionalInstructions": "Clean professional meeting brief, light background, one deep-orange accent, industrial imagery only, keep all names and figures exactly as written."})
        gid = r.json()["generationId"]
        print("generation", gid)
        url = None
        for _ in range(30):
            time.sleep(10)
            g = client.get(f"{GAMMA}/{gid}", headers={"X-API-KEY": os.environ["GAMMA_API_KEY"]}).json()
            if g.get("status") == "completed":
                url = g["gammaUrl"]
                break
            print("  ...", g.get("status"))
        if not url:
            raise SystemExit("gamma generation did not complete")
        client.post(f"{HS}/crm/v3/objects/notes", headers=hs_headers(), json={
            "properties": {"hs_note_body": f"Meeting brochure generated: {url}",
                           "hs_timestamp": int(time.time() * 1000)},
            "associations": [{"to": {"id": comp["id"]},
                              "types": [{"associationCategory": "HUBSPOT_DEFINED",
                                         "associationTypeId": 190}]}]})
        print(f"BROCHURE {comp['properties']['name']}: {url} (note posted on the account)")


if __name__ == "__main__":
    main()
